name: Build

on:
  push:
    branches:
      - main

concurrency:
  # Any pending or running executions is canceled in order to deploy once when multiple sequential changes.
  # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: cpina/github-action-push-to-another-repository@v1.7.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          destination-github-username: 'cachalot-app'
          destination-repository-name: 'cachalot-static'
          target-branch: main
          source-directory: '_site'
          target-directory: 'sites/www.brandhof.net'
          create-target-branch-if-needed: false
